image: "ubuntu:16.04"

before_script:
  - apt-get update -y && apt-get upgrade -y # Install updates
  - apt-get install binutils gcc-avr avr-libc uisp avrdude flex byacc bison make -y # Install needed packages

build:
  script:
    - cd Node1
    - make
    - cd ../Node2
    - make
