image: "ubuntu:16.04"

stages:
  - build_node_1
  - build_node_2

before_script:
  - apt-get update -y && apt-get upgrade -y # Install updates
  - apt-get install binutils gcc-avr avr-libc uisp avrdude flex byacc bison make -y # Install needed packages

build_node_1:
  script:
    - cd Node1
    - make

build_node_2:
  script:
    - cd Node2
    - make